conversation/urls.py
from django.urls import path
from. import views

app_name='conversation'


urlpatterns = [
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
    path('',views.inbox,name='inbox'),
    path('/<int:pk>/',views.detail,name='detail')
]

core/urls.py
from django.urls import path
from .views import index
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

urlpatterns = [
    path('',views.index,name="index"),
    path('contact/',views.contact,name="contact"),
    path('signup/',views.sign_up,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    #login redirect defined in settings.py LOGIN_REDIRECT_URL='/'
]

dashboard/urls.py
from django.urls import path
from . import views
app_name='dashboard'

urlpatterns = [
    path('',views.index,name='index'),
]

item/urls.py
from django.urls import path
from .import views


app_name='item'

urlpatterns = [
    path('<int:pk>/',views.detail,name='detail'),
    path('additem/',views.Addnewitem,name='additem'),
    path('<int:pk>/delete/',views.DeleteItem,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    path('',views.items,name='items')]

market_place/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)#path for media(images )

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model= User
        fields=('username','email','password1','password2')


        username=forms.CharField(widget=forms.TextInput(attrs={
            'placeholder':'your username',
            'class':"w-full py-4 px-6 rounded-xl"
        }))

        emails=forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder':'Your username',
            'class':'w-full py-4 px-6 rounded-xl'
        }))

        password1=forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder':'password',
            'class':'w-full py-4 px-6 rounded-xl'
        }))

        password2=forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder':'repeat password',
            'class':'w-full py-4 px-6 rounded-xl'
        }))

class LoginForm(AuthenticationForm):
     username=forms.CharField(widget=forms.TextInput(attrs={
            'placeholder':'your username',
            'class':"w-full py-4 px-6 rounded-xl"
        }))
     password=forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder':'password',
            'class':'w-full py-4 px-6 rounded-xl'
        }))

core/views.py
from django.shortcuts import render,redirect
from item.models import Item,Category,User
from .forms import SignupForm,LoginForm


# Create your views here.
def index(request):
    items=Item.objects.filter(is_sold=False)[0:6]
    categories=Category.objects.all()
    return render(request,'core/index.html',{'items':items,'categories':categories})

def contact(request):
    return render(request,"core/contact.html")

def sign_up(request):
    
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('login')
    else:
        form=SignupForm()

    return render(request,'core/sign_up.html',{'form':form})
        
def log_in(request):
   pass
# log in view created at urls.py  

core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Marketplace </title><br>
</head>
<body>

    <nav class="py-6 px-6 flex justife-between items-center border-b border-gray-200">
        <a href="/" class="test-xl font-semibold">Marketplace</a>

        <div class="space-x-6">
            <a href="" class="text-lg font-semibold hover:text-gray-500">New item!</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %}
            <a href="{% url 'item:additem' %}" class="text-lg font-semibold hover:text-gray-500">New item!</a>
            <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover::bg-teal-500">Inbox</a>
            <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover::bg-gray-500">Dashboard</a>
            {% else %}
            <a href="{% url 'signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover::bg-teal-500">Sign up</a>
            <a href="{% url 'login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover::bg-gray-500">Log in</a>
            {% endif %}

        </div>

    </nav>
    <div class="px-6 py-6">
    
     {% block content %}
        

     {% endblock %}
     </div>
     <footer class="py-6 px-6 flex justife-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb=5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-white"> fewefwfwf</p>
        </div>
        <div class="w-1/3"> 
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="" class="test-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'contact' %}" class="test-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="" class="test-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="" class="test-lg text-teal-500 hover:text-teal-700">Terms</a></li>
            </ul>
        </div>
     </footer>



   

    
</body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}
{% block content %}
<h1>contact</h1>   
{% endblock %}

core/templates/core/index.html
nes (37 sloc)  1.47 KB

{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in up</h1>
    <form action="" method="POST">
        {% csrf_token %}
           
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password}}
        </div>
     
        {% if form.errors or non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form  %}
            {{field.errors}}
        {% endfor %}
        {{form.non_field_errors}}
    </div>  
        {% endif %}

        

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700" type="submit">submit</button>
    </form>
</div>

{% endblock content %}

core/templates/core/sign_up.html
{% extends 'core/base.html' %}
{% block tittle %}Sign up{% endblock tittle %}


{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
    </form>
</div>

{% endblock content %}